repos:
#-   repo: https://github.com/PyCQA/isort
#    rev: 5.12.0
#    hooks:
#    -   id: isort
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
    -   id: ruff
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-ast
#-   repo: https://github.com/PyCQA/flake8
#    rev: 6.0.0
#    hooks:
#    -   id: flake8
#        args: ['--max-line-length=120',]
